/**
 * 
 */
package com.evaluateyourself.model;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * @author Mateusz Miernik [mateusz.miernik86@gmail.com]
 * This class represents information about single user. 
 */
@Entity
@Table(name="users", schema="public")
public class Users implements Serializable{
	
	private static final long serialVersionUID = -3041495761267330339L;
	
	/**
	 * User Id property represents primary key in database.
	 */
	@Id
	@Column(name="usid", nullable=false, unique=true)
	@GeneratedValue
	private int usid;

	/**
	 * User first name.
	 */
	@Column(name="usfirstname", nullable=true, length=45)
	private String usfirstname;
	
	/**
	 * User last name.
	 */
	@Column(name="uslastname", nullable=true, length=45)
	private String uslastname; 
	
	/**
	 * Specify date, when user joined to the community. Set current date as default  
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="usjoindate", insertable=false, updatable=false)
	private Date usjoindate;
	
	/**
	 * User login to system.
	 */
	@Column(name="uslogin", length=40, insertable=true, updatable=false)
	private String uslogin;
	
	/**
	 * User email address.
	 */
	@Column(name="usemail", nullable=false, length=60, insertable=true, updatable=false, unique=true)
	private String usemail;
	
	/**
	 * User encrypted password by bcrypt algorithm.  
	 */
	@Column(name="uspassword", nullable=false, length=500, insertable=true, updatable=false)
	private String uspassword;
	
	
	@Column(name="usrole", nullable=false, length=10, insertable=true, updatable=true)
	private String usrole;
	
	/**
	 * Collection rows of {@link com.evaluateyourself.model.UsersInformations UsersInformations} 
	 */
	@OneToMany(cascade=CascadeType.REMOVE, mappedBy="uiusid")
	private Collection<UsersInformations> usersInfromationsColl;
	
	@Column(name="usautogeneratedlink", length51)
    private String usautogeneratedlink;
    
	@Column(name="usisconfirmed")
    private boolean usisconfirmed = false;
	
	
	public Users(){
		
	}
	
	/**
	 * @param uslogin User login 
	 * @param usemail User email address
	 * @param uspassword User password
	 */
	public Users(String uslogin, String usemail, String uspassword) {
		super();
		this.uslogin = uslogin;
		this.usemail = usemail;
		this.uspassword = uspassword;
	}
	
	/**
	 * @return the usid
	 */
	public int getUsid() {
		return usid;
	}

	/**
	 * @param usid the usid to set
	 */
	public void setUsid(int usid) {
		this.usid = usid;
	}

	/**
	 * @return the usfirstname
	 */
	public String getUsfirstname() {
		return usfirstname;
	}

	/**
	 * @param usfirstname the usfirstname to set
	 */
	public void setUsfirstname(String usfirstname) {
		this.usfirstname = usfirstname;
	}

	/**
	 * @return the uslastname
	 */
	public String getUslastname() {
		return uslastname;
	}

	/**
	 * @param uslastname the uslastname to set
	 */
	public void setUslastname(String uslastname) {
		this.uslastname = uslastname;
	}

	/**
	 * @return the usjoindate
	 */
	public Date getUsjoindate() {
		return usjoindate;
	}

	/**
	 * @param usjoindate the usjoindate to set
	 */
	public void setUsjoindate(Date usjoindate) {
		this.usjoindate = usjoindate;
	}

	/**
	 * @return the uslogin
	 */
	public String getUslogin() {
		return uslogin;
	}

	/**
	 * @param uslogin the uslogin to set
	 */
	public void setUslogin(String uslogin) {
		this.uslogin = uslogin;
	}

	/**
	 * @return the usemail
	 */
	public String getUsemail() {
		return usemail;
	}

	/**
	 * @param usemail the usemail to set
	 */
	public void setUsemail(String usemail) {
		this.usemail = usemail;
	}

	/**
	 * @return the uspassword
	 */
	public String getUspassword() {
		return uspassword;
	}

	/**
	 * @param uspassword the uspassword to set
	 */
	public void setUspassword(String uspassword) {
		this.uspassword = uspassword;
	}

	/**
	 * @return the usersInfromationsColl
	 */
	public Collection<UsersInformations> getUsersInfromationsColl() {
		return usersInfromationsColl;
	}

	/**
	 * @param usersInfromationsColl the usersInfromationsColl to set
	 */
	public void setUsersInfromationsColl(Collection<UsersInformations> usersInfromationsColl) {
		this.usersInfromationsColl = usersInfromationsColl;
	}
	
	
	public String getUsrole() {
		return usrole;
	}

	public void setUsrole(String usrole) {
		this.usrole = usrole;
	}
	
	
	
	public String getUsautogeneratedlink() {
		return usautogeneratedlink;
	}

	public void setUsautogeneratedlink(String usautogeneratedlink) {
		this.usautogeneratedlink = usautogeneratedlink;
	}

	public boolean isUsisconfirmed() {
		return usisconfirmed;
	}

	public void setUsisconfirmed(boolean usisconfirmed) {
		this.usisconfirmed = usisconfirmed;
	}

	

	@Override
	public String toString() {
		return "Users [usid=" + usid + ", usfirstname=" + usfirstname + ", uslastname=" + uslastname + ", usjoindate="
				+ usjoindate + ", uslogin=" + uslogin + ", usemail=" + usemail + ", uspassword=" + uspassword
				+ ", usrole=" + usrole + ", usersInfromationsColl=" + usersInfromationsColl + ", usautogeneratedlink="
				+ usautogeneratedlink + ", usisconfirmed=" + usisconfirmed + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + usid;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Users other = (Users) obj;
		if (usid != other.usid)
			return false;
		return true;
	}

	
	
	
}
