/**
 * 
 */
package com.evaluateyourself.service.impl;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.evaluateyourself.dao.UsersDao;
import com.evaluateyourself.exceptions.UserWithEmailExist;
import com.evaluateyourself.model.Users;
import com.evaluateyourself.service.UsersManager;
import com.evaluateyourself.utils.DataFormatter;

/**
 * @author Mateusz [mateusz.miernik86@gmail.com]
 *
 */
@Service
public class UsersManagerImpl implements UsersManager {
	
	private Logger logger = LoggerFactory.getLogger(UsersManagerImpl.class);
	
	@Autowired
	UsersDao usersdao;
	
	@Autowired
	MailService mailService;

	@Override
	@Transactional
	public Users create(Users user) {
		return usersdao.create(user);
	}

	@Override
	@Transactional(readOnly=true)
	public Users get(Serializable id) {
		return usersdao.get(id);
	}

	@Override
	@Transactional(readOnly=true)
	public Users load(Serializable id) {
		return usersdao.load(id);
	}
	
	@Override
	@Transactional(readOnly=true)
	public Map<Integer,Users> getAll() {
		
		Map<Integer,Users> result = new HashMap<Integer,Users>();
		List<Users> resultList = usersdao.getAll();
		for(Users usr: resultList){
			result.put(usr.getUsid(), usr);
		}
		return result;
	}

	@Override
	@Transactional
	public Users update(Users user) {
		usersdao.update(user);
		return user;
	}

	@Override
	@Transactional
	public void delete(Users user) {
		usersdao.delete(user);
	}

	@Override
	@Transactional
	public void deleteById(Serializable id) {
		usersdao.deleteById(id);
	}

	@Override
	@Transactional
	public void deleteAll() {
		usersdao.deleteAll();
	}

	@Override
	@Transactional(readOnly=true)
	public long count() {
		return usersdao.count();
	}

	@Override
	@Transactional(readOnly=true)
	public boolean exist(Serializable id) {
		return usersdao.exist(id);
	}

	@Override
	@Transactional
	public Users registerUser(Users usr){
		String decodedEmail = DataFormatter.DecodeStringBase64(usr.getUsemail());
		Users user = usersdao.findByEmail(decodedEmail);
		logger.info("User finded in registerUser method: " + user);
		
		if(user == null)
		{
			//We can add new user to database
			user = new Users();
			user.setUsemail(decodedEmail);
			user.setUspassword(DataFormatter.encodePassword(DataFormatter.DecodeStringBase64(usr.getUspassword())));
			user.setUsautogeneratedlink(DataFormatter.buildRandomString(50));
			user.setUsisconfirmed(false);
			user.setUsroles("user");
			usersdao.create(user);
			//sendConfirmationEmail(user.getUsemail(), user.getUsautogeneratedlink());
			return user;
		}
		else
		{
			throw new UserWithEmailExist("User with " + decodedEmail + " already exist in database");
		}
	}
	private void sendConfirmationEmail(String email, String link){
		
		//mailService.sendEmail(email, "Confirmation Link Below", body);
	}
	

}
